/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * DH - Piskotki
 * API for DH - Piskotki
 * OpenAPI spec version: 1.0
 */

export type BookStatus = (typeof BookStatus)[keyof typeof BookStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BookStatus = {
  AVAILABLE: 'AVAILABLE',
  BORROWED: 'BORROWED',
  IN_TRANSTT: 'IN_TRANSTT',
  LOST: 'LOST',
} as const;
