/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * DH - Piskotki
 * API for DH - Piskotki
 * OpenAPI spec version: 1.0
 */
import type { Book } from './book';
import type { User } from './user';

export interface BookReservation {
  id: string;
  createdAt: string;
  updatedAt: string;
  book: Book;
  bookId: string;
  user: User;
  userId: string;
}
