/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * DH - Piskotki
 * API for DH - Piskotki
 * OpenAPI spec version: 1.0
 */
import type { BookStatus } from './bookStatus';
import type { BookReservation } from './bookReservation';
import type { User } from './user';

export interface Book {
  id: string;
  createdAt: string;
  updatedAt: string;
  status: BookStatus;
  title: string;
  author: string;
  description: string;
  coverUrl: string;
  isbn: string;
  price?: number;
  reservations: BookReservation[];
  owner: User;
  ownerId: string;
  borrower?: User;
  borrowerId?: string;
  borrowDate?: string;
  returnDate?: string;
}
