/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * DH - Piskotki
 * API for DH - Piskotki
 * OpenAPI spec version: 1.0
 */

export interface RegisterUserDto {
  email: string;
  password: string;
  firstName: string;
  lastName: string;
}
