/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * DH - Piskotki
 * API for DH - Piskotki
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';

export interface UserReview {
  id: string;
  createdAt: string;
  updatedAt: string;
  rating: number;
  review: string;
  author: User;
  userId: string;
  subject: User;
  subjectId: string;
}
